# .github/workflows/ci.yml
name: CI

on:
  # Run when a pull request is opened, synchronized (new commits), or reopened
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Lint (ESLint)
        run: npm run lint

      - name: Prettier (format check)
        run: npm run prettier -- --check .

      - name: Run tests (Jest)
        env:
          CI: true
        run: npm test -- --watchAll=false

      - name: Build
        run: npm run build
