name: Hello World Workflow

# Trigger workflow when code is pushed to master branch
on:
  push:
    branches:
      - master

jobs:
  say-hello:
    runs-on: ubuntu-latest   # GitHub gives you a free Ubuntu VM
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
